version: 2

builds:
  - id: kubesleep
    main: ./cmd/kubesleep/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/Y0-L0/kubesleep/kubesleep/version.Version=v{{ .Version }}
      - -X github.com/Y0-L0/kubesleep/kubesleep/version.Commit={{ .ShortCommit }}
      - -X github.com/Y0-L0/kubesleep/kubesleep/version.BuildDate={{ .Date }}
      - -X github.com/Y0-L0/kubesleep/kubesleep/version.TreeState={{ if .IsGitDirty }}dirty{{ else }}clean{{ end }}

nfpms:
  - id: linux-packages
    package_name: kubesleep
    ids:
      - kubesleep
    vendor: stadimeter
    homepage: https://github.com/Y0-L0/kubesleep
    maintainer: "y0-l0 <jojo.dev@lohmer.com>"
    description: Suspend and wake Kubernetes workloads on a schedule
    license: AGPL-3.0
    formats:
      - deb
    bindir: /usr/bin

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

dockers_v2:
  - images:
      - ghcr.io/y0-l0/kubesleep
    dockerfile: Dockerfile.distroless
    tags:
      - "{{ .Version }}"
      - latest
    labels:
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .ShortCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"

homebrew_casks:
  - repository:
      owner: y0-l0
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    homepage: https://github.com/Y0-L0/kubesleep
    description: Suspend and wake Kubernetes workloads on a schedule
    license: AGPL-3.0

publishers:
  - name: fury
    ids:
      - linux-packages
    checksum: false
    signature: false
    dir: "{{ dir .ArtifactPath }}"
    cmd: "curl -v -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/{{ .Env.FURY_ACCOUNT }}/"

changelog:
  sort: asc
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - '^ci:'
